/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;
import Con.ContFilas;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
/**
 *
 * @author rosaura
 */
public class VistaFilas extends javax.swing.JFrame {
    private ContFilas cont;

    public JTextArea getTalistos() {
        return talistos;
    }

    public ContFilas getCont() {
        return cont;
    }

    public void setCont(ContFilas cont) {
        this.cont = cont;
    }

    public JButton getBtnanadir() {
        return btnanadir;
    }


    public JTextArea getTafilas() {
        return tafilas;
    }

    public JLabel getLbanadir() {
        return lbanadir;
    }

    public JLabel getLbarti() {
        return lbarti;
    }

    public JLabel getLbfila() {
        return lbfila;
    }

    public JTextField getTfart() {
        return tfart;
    }

    public JTextField getTffila() {
        return tffila;
    }
    
    /**
     * Creates new form VistaFilas
     */
    public VistaFilas() {
        initComponents();
        btnanadir.setEnabled(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tafilas = new javax.swing.JTextArea();
        lbanadir = new javax.swing.JLabel();
        lbfila = new javax.swing.JLabel();
        lbarti = new javax.swing.JLabel();
        btnanadir = new javax.swing.JButton();
        tffila = new javax.swing.JTextField();
        tfart = new javax.swing.JTextField();
        lbFil = new javax.swing.JLabel();
        lbcli = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        talistos = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tafilas.setColumns(20);
        tafilas.setRows(5);
        jScrollPane1.setViewportView(tafilas);

        lbanadir.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lbanadir.setText("Añadir cliente a la fila:");

        lbfila.setText("Fila:");

        lbarti.setText("No. de artículos:");

        btnanadir.setText("Añadir");
        btnanadir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnanadirMouseClicked(evt);
            }
        });

        tfart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfartActionPerformed(evt);
            }
        });
        tfart.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfartKeyTyped(evt);
            }
        });

        lbFil.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lbFil.setText("Info filas:");

        lbcli.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lbcli.setText("Info clientes:");

        talistos.setColumns(20);
        talistos.setRows(5);
        jScrollPane3.setViewportView(talistos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbfila)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tffila, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(65, 65, 65))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnanadir, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbanadir)
                                    .addComponent(lbarti))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tfart, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(65, 65, 65))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbcli)
                            .addComponent(lbFil)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(lbFil)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lbcli)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                        .addGap(34, 34, 34))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbanadir)
                                .addGap(18, 18, 18)
                                .addComponent(lbfila))
                            .addComponent(tffila, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbarti)
                                    .addComponent(tfart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnanadir)
                                .addGap(34, 34, 34))))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfartActionPerformed
    }//GEN-LAST:event_tfartActionPerformed

    private void tfartKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfartKeyTyped
        if(tffila.getText()!=null){
            btnanadir.setEnabled(true);
        }
    }//GEN-LAST:event_tfartKeyTyped

    private void btnanadirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnanadirMouseClicked
        cont.nuevoC((int) Double.parseDouble(tffila.getText()), (int) Double.parseDouble(tfart.getText()));
        tffila.setText("");
        tfart.setText("");
    }//GEN-LAST:event_btnanadirMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaFilas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaFilas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaFilas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaFilas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaFilas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnanadir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbFil;
    private javax.swing.JLabel lbanadir;
    private javax.swing.JLabel lbarti;
    private javax.swing.JLabel lbcli;
    private javax.swing.JLabel lbfila;
    private javax.swing.JTextArea tafilas;
    private javax.swing.JTextArea talistos;
    private javax.swing.JTextField tfart;
    private javax.swing.JTextField tffila;
    // End of variables declaration//GEN-END:variables
}
